name: Kafka2i

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-musl
    - name: muscl-tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools
    - name: build
      env:
        # required for cross-compiling kerberos lib
        krb5_cv_attr_constructor_destructor: yes
      run: cargo build --release --target x86_64-unknown-linux-musl
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: kafka2i-linux-x86_64
        path: target/--target x86_64-unknown-linux-musl/release/kafka2i
  MacOs:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      run: cargo build --release
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: kafka2i-macos-arm64
        path: target/release/kafka2i
