name: Kafka2i

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: cargo build --release
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: kafka2i-linux-x86_64
        path: target/release/kafka2i
  MacOs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: cargo build --release
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: kafka2i-macos-arm64
        path: target/release/kafka2i
